apiVersion: v1
data:
  accessKeyId: TUlTU0lORw==
kind: Secret
metadata:
  labels:
    app: signalsciences-signalsciences
    release: signalsciences
  name: signalsciences-signalsciences-accesskeyid
type: Opaque
---
apiVersion: v1
data:
  secretAccessKey: TUlTU0lORw==
kind: Secret
metadata:
  labels:
    app: signalsciences-signalsciences
    release: signalsciences
  name: signalsciences-signalsciences-secretaccesskey
type: Opaque
